#!/usr/bin/env python3
"""Generate a per-project reprojection plan from laz-by-project.csv.

Target: metric, conformal, low-distortion State Plane (NAD83(2011)) in the
correct zone for each project, with NAVD88 height (metres) vertical.

Zone assignment:
  * Projects already tagged with a Florida State Plane zone keep that zone.
  * UTM / Conus Albers projects (and Georgia projects) get a zone inferred
    from their centroid longitude/latitude. Boundaries are approximate
    (real SPCS zones follow county lines) but always pick a conformal zone
    whose central meridian is close to the data -> low distortion.

Outputs (written next to this script):
  reprojection-plan.csv   one row per project: source + target CRS
  reproject.sh            generated pdal translate commands
"""
import csv, re, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "laz-by-project.csv")

# Metric NAD83(2011) State Plane EPSG codes (verified via projinfo)
ZONE_EPSG = {
    "FL East": 6437, "FL North": 6440, "FL West": 6442,
    "GA East": 6444, "GA West": 6446,
}
VERTICAL = 5703  # NAVD88 height (metres)

# Vertical codes we trust as already-NAVD88 (only units/realization differ)
NAVD88 = {"EPSG:5703", "EPSG:6360"}


def centroid(wkt):
    pts = re.findall(r"(-?\d+\.\d+)\s+(-?\d+\.\d+)", wkt)
    xs = [float(a) for a, _ in pts]
    ys = [float(b) for _, b in pts]
    return sum(xs) / len(xs), sum(ys) / len(ys)


def zone_for(name, lon, lat, hproj):
    if name.startswith("GA_"):                       # Georgia: split ~ -83.2
        return "GA East" if lon >= -83.2 else "GA West"
    if "Florida East"  in hproj: return "FL East"    # keep tagged FL zone
    if "Florida North" in hproj: return "FL North"
    if "Florida West"  in hproj: return "FL West"
    # infer for UTM / Albers Florida sources
    if lat >= 29.5 and lon <= -82.0: return "FL North"   # panhandle / north
    if lon <= -81.7:                 return "FL West"     # gulf peninsula
    return "FL East"                                      # atlantic peninsula


def main():
    rows = list(csv.DictReader(open(SRC)))
    plan = []
    for r in rows:
        lon, lat = centroid(r["geometry"])
        zone = zone_for(r["project"], lon, lat, r["horizontal_projection"])
        sh = r["horizontal_epsg"].strip()
        sv = r["vertical_epsg"].strip()
        v_ok = sv in NAVD88
        plan.append({
            "project": r["project"],
            "files": r["files"],
            "lon": round(lon, 3), "lat": round(lat, 3),
            "source_h": sh,
            "source_v": sv or "(none)",
            "target_zone": zone,
            "target_h": f"EPSG:{ZONE_EPSG[zone]}",
            "target_v": f"EPSG:{VERTICAL}",
            # full out_srs: only attach vertical when source vertical is known
            "out_srs": (f"EPSG:{ZONE_EPSG[zone]}+{VERTICAL}" if v_ok
                        else f"EPSG:{ZONE_EPSG[zone]}"),
            "vertical_note": "" if v_ok else "CHECK vertical datum+units before Z reprojection",
        })

    cols = ["project", "files", "lon", "lat", "source_h", "source_v",
            "target_zone", "target_h", "target_v", "out_srs", "vertical_note"]
    with open(os.path.join(HERE, "reprojection-plan.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        w.writerows(plan)

    # generated reprojection script (one pdal translate per project)
    with open(os.path.join(HERE, "reproject.sh"), "w") as f:
        f.write("#!/usr/bin/env bash\n")
        f.write("# Generated by make_reprojection_plan.py -- edit the generator, not this file.\n")
        f.write("# Reproject each project to a metric, low-distortion State Plane zone.\n")
        f.write("# Usage: reproject.sh <in.laz> <out.laz> <PROJECT>\n")
        f.write("set -euo pipefail\n\nIN=$1; OUT=$2; PROJECT=$3\ncase \"$PROJECT\" in\n")
        for p in plan:
            # compound CRS: vertical code goes in bare after '+', e.g. EPSG:26917+5703
            sv_bare = p["source_v"].replace("EPSG:", "")
            in_srs = f' --filters.reprojection.in_srs="{p["source_h"]}+{sv_bare}"' \
                     if p["source_v"] != "(none)" and "CHECK" not in p["vertical_note"] else \
                     f' --filters.reprojection.in_srs="{p["source_h"]}"'
            f.write(f'  {p["project"]})\n')
            f.write(f'    pdal translate "$IN" "$OUT" reprojection'
                    f'{in_srs}'
                    f' --filters.reprojection.out_srs="{p["out_srs"]}" ;;\n')
        f.write('  *) echo "unknown project: $PROJECT" >&2; exit 1 ;;\nesac\n')

    # summary to stdout
    from collections import Counter
    print("Target zone distribution:")
    for z, c in Counter(p["target_zone"] for p in plan).most_common():
        print(f"  {z:9} {c:3}  -> EPSG:{ZONE_EPSG[z]}")
    flagged = [p["project"] for p in plan if p["vertical_note"]]
    print(f"\n{len(plan)} projects, {sum(int(p['files']) for p in plan)} files")
    print(f"{len(flagged)} need vertical confirmation: {', '.join(flagged)}")
    print("\nwrote reprojection-plan.csv and reproject.sh")


if __name__ == "__main__":
    main()
