#!/usr/bin/env bash
# Generated by make_reprojection_plan.py -- edit the generator, not this file.
# Reproject each project to a metric, low-distortion State Plane zone.
# Usage: reproject.sh <in.laz> <out.laz> <PROJECT>
set -euo pipefail

IN=$1; OUT=$2; PROJECT=$3
case "$PROJECT" in
  FL_2017FortDrum_1_C22)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_2017PalmCoast_1_C22)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_2018PascoCounty_1_C22)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Everglades_N_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Everglades_N_Hydroflattened_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Everglades_S_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Everglades_S_Hydroflattened_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26917+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_HurricaneMichael_1_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_HurricaneMichael_2_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_HurricaneMichael_3_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_HurricaneMichael_4_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_HurricaneMichael_5_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_HurricaneMichael_6_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238" --filters.reprojection.out_srs="EPSG:6440" ;;
  FL_HurricaneMichael_7_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_LeonCo_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6441+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Lower_Choctawhatchee_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:26916+5703" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_ManateeCo_1_B25)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_MiamiDade_1_D23)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Osceola_2015)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_PalmBeachCo_2016)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6438" --filters.reprojection.out_srs="EPSG:6437" ;;
  FL_Panhandle_B1_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350" --filters.reprojection.out_srs="EPSG:6440" ;;
  FL_Panhandle_B2_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350" --filters.reprojection.out_srs="EPSG:6440" ;;
  FL_Panhandle_TL_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350" --filters.reprojection.out_srs="EPSG:6440" ;;
  FL_PeaceRiver_2014)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6442" --filters.reprojection.out_srs="EPSG:6442" ;;
  FL_Peninsular_Citrus_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Alachua_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Baker_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Bradford_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Brevard_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Charlotte_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Clay_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Collier_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Columbia_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Desoto_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Dixie_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Duval_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Gilchrist_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Glades_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Hamilton_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Hardee_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Hendry_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Highlands_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_IndianRiver_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_KeyBiscayne_2020)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Lafayette_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Madison_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Manatee_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Martin_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Nassau_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Okeechobee_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Orange_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236" --filters.reprojection.out_srs="EPSG:6437" ;;
  FL_Peninsular_FDEM_Osceola_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_PalmBeach_2019)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Polk_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_Sarasota_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_FDEM_StJohns_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_StLucie_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_FDEM_Suwannee_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Taylor_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_FDEM_Union_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238+6360" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  FL_Peninsular_Flagler_2019)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_Hernando_2019)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_Lake_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_Levy_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_Marion_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_Pinellas_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_Putnam_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_Seminole_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Peninsular_Sumter_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2237+6360" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Peninsular_Volusia_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2236+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Southeast_B1_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Southeast_B2_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Southeast_TL_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Southwest_A_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6442+5703" ;;
  FL_Southwest_B_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Southwest_B_TL_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Suwannee_NCentral_2014)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:2238" --filters.reprojection.out_srs="EPSG:6440" ;;
  FL_TopobathyFLKeysNOAA_Hydroflattened_2019)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6346+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_Upper_Saint_Johns_2017)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6438+6360" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  FL_WestEvergladesNP_topobathymetric_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6437+5703" ;;
  GA_Statewide_10_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6444+5703" ;;
  GA_Statewide_11_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6444+5703" ;;
  GA_Statewide_12_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6444+5703" ;;
  GA_Statewide_9_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6444+5703" ;;
  GA_Statewide_B1_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6446+5703" ;;
  GA_Statewide_B2_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6446+5703" ;;
  GA_Statewide_B3_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350+5703" --filters.reprojection.out_srs="EPSG:6446+5703" ;;
  USGS_LPC_FL_GulfCoast_Topography_2018)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6345+5703" --filters.reprojection.out_srs="EPSG:6440+5703" ;;
  USGS_LPC_FL_Panhandle_B3_2018_LAS_2019)
    pdal translate "$IN" "$OUT" reprojection --filters.reprojection.in_srs="EPSG:6350" --filters.reprojection.out_srs="EPSG:6440" ;;
  *) echo "unknown project: $PROJECT" >&2; exit 1 ;;
esac
